[build]
  publish = "build/client"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optionally allow direct access to assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
